server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9761/eureka/
    
zuul:
  #Service will be mapped under the /api URI
  prefix: /api
#  Uncomment to disable auto-registering all services read from Eureka
#  ignoredServices: '*'
  routes:
    composite:
      path: /aggregator/**
      serviceId: AGGREGATOR
    product:
      path: /product/**
      serviceId: PRODUCT-SERVICE

spring:
  application:
    name: zuul-server